sudo: false
dist: trusty

language: go

# Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
env:
  global:
    - CC_TEST_REPORTER_ID=5b83cb480af2b962400b3ccc8ffd43727e0f3937d638a4daaf1087431f582dda

go:
  - 1.14.x

# addons:
#   sonarcloud:
#     organization: "devopsworks"

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -coverprofile=c.out -v -race ./...  # Run all the tests with the race detector enabled
  - make build
    #  - sonar-scanner -X

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT